### ISSUE TITLE
warning: possible EventEmitter memory leak detected. 11 reset listeners added.

### ISSUE THREAD

**Issue by mike-zorn** [Updater/browserify-resolutions#13]
When using this in conjunction with watchify, after a few updates this warning starts to appear.

```
(node) warning: possible EventEmitter memory leak detected. 11 reset listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Browserify.addListener (events.js:239:17) 
    at module.exports (/Users/matkins/env/dev/ui/node_modules/browserify-resolutions/index.js:35:13)
    at Browserify.plugin (/Users/matkins/env/dev/ui/node_modules/browserify/index.js:349:9)
    at Browserify.<anonymous> (/Users/matkins/env/dev/ui/gulp/tasks/browserify.js:21:17)
    at emitOne (events.js:77:13)
    at Browserify.emit (events.js:169:7)
    at notify [as _onTimeout] (/Users/matkins/env/dev/ui/node_modules/watchify/index.js:149:15)
    at Timer.listOnTimeout (timers.js:92:15)
```

This appears to come from [reattaching the plugins](https://github.com/Updater/browserify-resolutions/blob/master/index.js#L35).

**Comment by pmowrer** [comment]
Which versions of browserify and watchify are you seeing this in?

**Comment by mike-zorn** [comment]
- browserify 10.2.6
- watchify 3.4.0
- browserify-resolutions 1.0.6

**Comment by mike-zorn** [comment]
node 4.2.2

**Comment by pmowrer** [comment]
I don't think it has to do with the `applyPlugins` method but rather the listener added for the `reset` event (which then calls `applyPlugins`). I don't see a scenario in which this library applies that listener multiple times though, unless the library itself is being applied many times (which is likely outside of its control). Perhaps you can help debug by checking whether `browserify-resolutions`'s main method is being called multiple times (and if so, why). 

Another possibility is that something else in your Browserify configuration is adding multiple `reset` listeners close to the limit and `browserify-resolutions` adds the listener that pushes the max listeners threshold.

**Comment by mike-zorn** [comment]
Thanks for your debugging tips! The plugin was being rerun on watch because I had configured things incorrectly. Sorry for bugging you with a non-issue and thanks, again!

**Comment by pmowrer** [comment]
Happy to help. Glad it worked out!
