### ISSUE TITLE
Module name check is unsafe

### ISSUE THREAD

**Issue by ahutchings** [Updater/browserify-resolutions#2]
The [module name matcher](https://github.com/Updater/browserify-resolutions/blob/master/index.js#L98) could inadvertently match unintended modules. For example, if a user set "react" as the option value, all module names containing the string "react" would be deduped. This may be a contrived use case since the only valid string is "*", but you might want to consider checking that options is an array before using `indexOf`.

**Comment by pmowrer** [comment]
Good point! It's a little rough around the edges and could certainly use some help preventing people from falling into traps
