### ISSUE TITLE
Unsafe to assume that the first "file" emitted after a "package" is the package main

### ISSUE THREAD

**Issue by ahutchings** [Updater/browserify-resolutions#5]
When requiring a file inside a module like `require('react/addons')` or `require('lodash/array/uniq')`, the first "file" emitted will be the required file (ex. "react/addons.js"), not the package main.

I don't know what the implications of this are, but wanted to let you know since you left a comment questioning the logic: https://github.com/Updater/browserify-resolutions/blob/b7c04dee407496c454cf4ba5d9f29f29b75e6e73/index.js#L120

**Comment by pmowrer** [comment]
I'm not sure I follow the examples... there aren't packages associated with those requires. Either way, this is definitely something I'd like to address. Unfortunately, it doesn't appear like there's an easy hook for retrieving a package's main without duplicating the work already done by `module-deps`.

**Comment by pmowrer** [comment]
Closing unless/until there is a demonstrable problem with this assumption.
